ethereum_rpc = "https://ethereum-holesky-rpc.publicnode.com"
drosera_rpc = "https://seed-node.testnet.drosera.io"
eth_chain_id = 17000
drosera_address = "0xea08f7d533C2b9A62F40D5326214f39a8E3A32F8"
private_key = "0d5321bd27dcb87156722be7713b45ad03bca8bb7e23d021e0530a0efc5c65d1"
gas_price = 10000

[traps]

[traps.mytrap]
path = "out/HelloWorldTrap.sol/HelloWorldTrap.json"
response_contract = "0xdA890040Af0533D98B9F5f8FE3537720ABf83B0C"
response_function = "responseCallback(uint256)"
cooldown_period_blocks = 40
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
address = "0xE8Cd39aF2D1524B87B07B752aaF4f3F54C7d28eC"
